### ISSUE TITLE
getting an error running CSCD()

### ISSUE THREAD

**Issue by NinnaFRC** [empiricalbayes/CSCDRNA#2]
Hello,

I follow the tutorial to run CSCD on the example data, but I got the error while running 
`analysis <- CSCD(bulk.eset=bulk.eset,sc.eset= sc.eset,
                 min.p=0.3,markers=NULL,cell.types="cellType",
                  subj.names="SubjectName", verbose=TRUE)`
> Decomposing into 4 cell types.
Warning: Data is of class matrix. Coercing to dgCMatrix.
Calculating cluster CT1
Warning: No layers found matching search pattern provided
Calculating cluster CT2
Warning: No layers found matching search pattern provided
Calculating cluster CT3
Warning: No layers found matching search pattern provided
Calculating cluster CT4
Warning: No layers found matching search pattern provided
Warning: No DE genes identified
Warning: The following tests were not performed:
Warning: When testing CT1 versus all:
Error evaluating 'x' argument while selecting method for 'rowSums' function: subscript out of bounds
Warning: When testing CT2 versus all:
Error evaluating 'x' argument while selecting method for 'rowSums' function: subscript out of bounds
Warning: When testing CT3 versus all:
Error evaluating 'x' argument while selecting method for 'rowSums' function: subscript out of bounds
Warning: When testing CT4 versus all:
Error evaluating 'x' argument while selecting method for 'rowSums' function: subscript out of bounds
Error in names(x) <- value :
   'names' attribute [2] must be the same length as the vector [0]
In addition: Warning messages:
1: Layer ‘data’ is empty
2: Layer ‘data’ is empty
3: Layer ‘data’ is empty
4: Layer ‘data’ is empty
5: Layer ‘data’ is empty
6: Layer ‘data’ is empty
7: Layer ‘data’ is empty
8: Layer ‘data’ is empty

How should I fix this problem? 
Thank you

**Comment by NinnaFRC** [comment]
The problem solved after turning seurat version from v5 to v4.

**Comment by empiricalbayes** [comment]
Thank you for raising the issue as well as the solution. The current version of CSCD is based on v4 of Seurat.
